name: Publish Docker image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKERREGISTRY_HOST }}
          username: ${{ vars.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      - name: get image name (stripping docker- prefix)
        id: strip_prefix
        run: |
          repo_name=${{ github.repository##*/ }}
          clean_name=${repo_name#docker-}
          echo "::set-output name=clean_repo_name::$clean_name"
      - name: get org name
        id: get_org
        run: |
          org_name=${{ github.repository%%/* }}
          echo "::set-output name=org_name::$org_name"
      - name: build and push docker image
        uses: docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: '' # https://gitea.com/gitea/act_runner/issues/119
        with:
          context: .
          no-cache: true
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERREGISTRY_HOST }}/${{ steps.get_org.outputs.org_name }}/${{ steps.strip_prefix.outputs.clean_repo_name }}:${{ github.ref_name }}
      - name: send telegram message
        uses: https://github.com/appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [Docker] ${{ steps.get_org.outputs.org_name }}/${{ steps.strip_prefix.outputs.clean_repo_name }}:${{ github.ref_name }} has just been released on ${{ vars.DOCKERREGISTRY_HOST }} 🎉
