name: Publish Docker image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKERREGISTRY_HOST }}
          username: ${{ vars.DOCKERREGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERREGISTRY_PASSWORD }}
      - name: Get image name (stripping docker- prefix)
        id: get_name
        run: |
          repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          image_name=${repo_name#docker-}
          echo "Repository name is: $repo_name"
          echo "Docker image name will be: $image_name"
          echo "::set-output name=image_name::$image_name"
      - name: Get org name
        id: get_org
        run: |
          org_name=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          echo "org name is: $org_name"
          echo "::set-output name=org_name::$org_name"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: '' # https://gitea.com/gitea/act_runner/issues/119
        with:
          context: .
          no-cache: true
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKERREGISTRY_HOST }}/${{ steps.get_org.outputs.org_name }}/${{ steps.get_name.outputs.image_name }}:${{ github.ref_name }}
      - name: Send job completion notification via Telegram
        uses: https://github.com/appleboy/telegram-action@master
        with:
          to: ${{ vars.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [Docker] ${{ steps.get_org.outputs.org_name }}/${{ steps.get_name.outputs.image_name }}:${{ github.ref_name }} has just been released on ${{ vars.DOCKERREGISTRY_HOST }} 🎉
